services:
  bookingsdb:
    image: mysql
    container_name: bookingsdb
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","bookingsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ragheb01276323608
      MYSQL_DATABASE: bookings

  paymentsdb:
    image: mysql
    container_name: paymentsdb
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","paymentsdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ragheb01276323608
      MYSQL_DATABASE: payments

  booking-service:
    image: booking-service
    container_name: booking-service
    build: ./booking-service
    depends_on:
      bookingsdb:
        condition: service_healthy
#    ports:
#      - '9090:9090'
    environment:
      MYSQL_HOST: bookingsdb
      DB_Name: bookings

  payment-service:
    image: payment-service
    container_name: payment-service
    build: ./payment-service
    depends_on:
      paymentsdb:
        condition: service_healthy
#    ports:
#      - '9091:9092'
    environment:
      MYSQL_HOST: paymentsdb
      DB_Name: payment

  com-services-registry:
    image: com-services-registry
    container_name: com.services.registry
    build: ./com-services-registry
    ports:
      - '8761:8761'

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - '8765:8765'
