spring:
  application:
    name: user-registration-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-service
#    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ragheb01276323608
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#email:
#  key:
#    api-key:48257sfhtthwauh
#    clientSecret=secret

server:
  port: 9091

