services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ragheb01276323608
      MYSQL_USER: root
      MYSQL_PASSWORD: ragheb01276323608
    ports:
      - '3307:3306'
  user-registration-service:
    image: ragheb045/user-registration-service
    restart: always
    depends_on:
      - mysqldb
    ports:
      - '8080:8080'
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USERNAME: root