spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: bookings-route
          uri:  lb://booking-service #http://localhost:8080/bookings/test
          predicates:
            - Path=/bookings/**
          filters:
            - name: CircuitBreaker # fallback mechanisms
              args:
                name: booking-route
                fallbackUri: forward:/booking-fallback
eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eurka/}

server:
  port: 8764
